// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/add_point.ts";
import * as $1 from "./routes/api/issue.ts";
import * as $2 from "./routes/api/login.ts";
import * as $3 from "./routes/demo.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/manage/[id].tsx";
import * as $$0 from "./islands/Login.tsx";
import * as $$1 from "./islands/PointCardIssueControl.tsx";
import * as $$2 from "./islands/PointCardManager.tsx";

const manifest = {
  routes: {
    "./routes/api/add_point.ts": $0,
    "./routes/api/issue.ts": $1,
    "./routes/api/login.ts": $2,
    "./routes/demo.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/manage/[id].tsx": $5,
  },
  islands: {
    "./islands/Login.tsx": $$0,
    "./islands/PointCardIssueControl.tsx": $$1,
    "./islands/PointCardManager.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
